### ISSUE TITLE
small issue your new update is incompatable with IC2 Exper builds

### ISSUE THREAD

**Issue by kurokuno** [Myrathi/ChargePadsEx#7]
sadly it crashes on startup due to invalid recipies being added

**Comment by MazerD** [comment]
Just made it here to report the same issue, thought I'd copy the log snippet in case it helps.
ChargePads 2.8.0.93 and IC2 2.0.67 experimental

2013-08-22 14:44:17 [FINEST] [ChargePads] Sending event FMLPostInitializationEvent to mod ChargePads
2013-08-22 14:44:17 [INFO] [STDOUT] IC2 API: Call getItem failed for nearDepletedUraniumCell
2013-08-22 14:44:17 [SEVERE] [ForgeModLoader] IndustrialCraft 2 Error

An invalid crafting recipe was attempted to be added. This could
happen due to a bug in IndustrialCraft 2 or an addon.

(Technical information: AdvRecipe, unknown type)
R: 1xitem.upgradeEmitterModule@1
O: null
T: null

**Comment by Myrathi** [comment]
Thanks to both for the details and sorry for the late reply (Minecraft Expo yadda yadda).

I'm aware the latest builds don't work alongside the experimental builds but that'll be dealt with as of the next update. Been kinda busy with 'stuff' and just hadn't got around to it. Soon™. ;)

**Comment by MazerD** [comment]
No worries, just wanted to be sure you were aware. Thanks for the mod! : )

**Comment by Myrathi** [comment]
v3.0.0 build 94 fixed this issue, at least.
